import type { ScenarioConfig } from '../types';

export const ecommerceConfig: ScenarioConfig = {
  id: 'ecommerce',
  icon: 'ShoppingCart',
  color: '#748ffc',
  events: [
    {
      type: 'order.created',
      label: 'Order Created',
      description: 'A new order is placed',
      defaultData: { total: 6500, isFirstOrder: false, customerTier: 'gold', items: 5 },
    },
    {
      type: 'order.cancelled',
      label: 'Order Cancelled',
      description: 'An order is cancelled',
      defaultData: { orderId: 'ORD-1234', reason: 'customer_request', refundAmount: 250 },
    },
    {
      type: 'payment.received',
      label: 'Payment Received',
      description: 'Payment is confirmed for an order',
      defaultData: { orderId: 'ORD-1234', amount: 6500, method: 'credit_card' },
    },
    {
      type: 'stock.updated',
      label: 'Stock Updated',
      description: 'Inventory stock level changes',
      defaultData: { productId: 'SKU-789', quantity: 5, productName: 'Wireless Mouse' },
    },
    {
      type: 'user.registered',
      label: 'User Registered',
      description: 'A new user creates an account',
      defaultData: { email: 'newuser@example.com', source: 'organic', country: 'TR' },
    },
    {
      type: 'cart.abandoned',
      label: 'Cart Abandoned',
      description: 'A shopping cart is abandoned',
      defaultData: { cartValue: 350, itemCount: 3, abandonedAfter: '2h' },
    },
    {
      type: 'review.submitted',
      label: 'Review Submitted',
      description: 'A product review is submitted',
      defaultData: { rating: 5, productId: 'SKU-456', hasPhoto: true },
    },
  ],
  actions: [
    { type: 'send_vip_email', label: 'Send VIP Email', description: 'Sends a VIP customer notification email' },
    { type: 'assign_priority_shipping', label: 'Priority Shipping', description: 'Assigns priority/express shipping' },
    { type: 'apply_discount', label: 'Apply Discount', description: 'Applies a discount to the order' },
    { type: 'send_welcome', label: 'Send Welcome', description: 'Sends a welcome message to the customer' },
    { type: 'notify_warehouse', label: 'Notify Warehouse', description: 'Alerts warehouse team about low stock' },
    { type: 'update_listing', label: 'Update Listing', description: 'Updates the product listing status' },
    { type: 'send_reminder_email', label: 'Send Reminder', description: 'Sends an abandoned cart reminder email' },
    { type: 'offer_discount', label: 'Offer Discount', description: 'Offers a discount to recover the cart' },
    { type: 'process_refund', label: 'Process Refund', description: 'Processes a refund for the order' },
    { type: 'update_inventory', label: 'Update Inventory', description: 'Updates inventory stock levels' },
    { type: 'send_confirmation', label: 'Send Confirmation', description: 'Sends a confirmation email' },
    { type: 'send_welcome_email', label: 'Send Welcome Email', description: 'Sends welcome email to new users' },
    { type: 'create_loyalty_account', label: 'Create Loyalty Account', description: 'Creates a loyalty rewards account' },
    { type: 'award_loyalty_points', label: 'Award Points', description: 'Awards loyalty reward points' },
    { type: 'feature_review', label: 'Feature Review', description: 'Features the review on the product page' },
    { type: 'update_order_status', label: 'Update Order Status', description: 'Updates the order status to confirmed' },
    { type: 'send_receipt', label: 'Send Receipt', description: 'Sends payment receipt to customer' },
    { type: 'trigger_fulfillment', label: 'Trigger Fulfillment', description: 'Triggers order fulfillment process' },
  ],
  rules: [
    {
      id: 'vip_order',
      label: 'VIP Order',
      description: 'When order total > $5000, send VIP email and assign priority shipping',
      group: 'orders',
      priority: 10,
      events: ['order.created'],
      matchMode: 'All',
      conditions: ['total gt 5000'],
      actions: ['send_vip_email', 'assign_priority_shipping'],
    },
    {
      id: 'first_order_discount',
      label: 'First Order Discount',
      description: 'When first order, apply 10% discount and send welcome',
      group: 'promotions',
      priority: 8,
      events: ['order.created'],
      matchMode: 'All',
      conditions: ['isFirstOrder eq true'],
      actions: ['apply_discount', 'send_welcome'],
    },
    {
      id: 'low_stock_alert',
      label: 'Low Stock Alert',
      description: 'When stock < 10 units, notify warehouse and update listing',
      group: 'inventory',
      priority: 7,
      events: ['stock.updated'],
      matchMode: 'All',
      conditions: ['quantity lt 10'],
      actions: ['notify_warehouse', 'update_listing'],
    },
    {
      id: 'abandoned_cart_recovery',
      label: 'Abandoned Cart Recovery',
      description: 'When cart value > $100 is abandoned, send reminder and offer discount',
      group: 'marketing',
      priority: 6,
      events: ['cart.abandoned'],
      matchMode: 'All',
      conditions: ['cartValue gt 100'],
      actions: ['send_reminder_email', 'offer_discount'],
    },
    {
      id: 'order_cancelled_refund',
      label: 'Order Cancelled',
      description: 'When order is cancelled, process refund, update inventory, send confirmation',
      group: 'orders',
      priority: 9,
      events: ['order.cancelled'],
      matchMode: 'All',
      conditions: [],
      actions: ['process_refund', 'update_inventory', 'send_confirmation'],
    },
    {
      id: 'new_user_welcome',
      label: 'New User Welcome',
      description: 'When user registers, send welcome email and create loyalty account',
      group: 'users',
      priority: 5,
      events: ['user.registered'],
      matchMode: 'All',
      conditions: [],
      actions: ['send_welcome_email', 'create_loyalty_account'],
    },
    {
      id: 'high_rating_reward',
      label: 'High Rating Reward',
      description: 'When 5-star review submitted, award loyalty points and feature review',
      group: 'reviews',
      priority: 4,
      events: ['review.submitted'],
      matchMode: 'All',
      conditions: ['rating gte 5'],
      actions: ['award_loyalty_points', 'feature_review'],
    },
    {
      id: 'payment_confirmed',
      label: 'Payment Confirmed',
      description: 'When payment received, update status, send receipt, trigger fulfillment',
      group: 'payments',
      priority: 10,
      events: ['payment.received'],
      matchMode: 'All',
      conditions: [],
      actions: ['update_order_status', 'send_receipt', 'trigger_fulfillment'],
    },
  ],
};
