import type { ScenarioConfig } from '../types';

export const rpgGameConfig: ScenarioConfig = {
  id: 'rpgGame',
  icon: 'Sword',
  color: '#ff6b6b',
  events: [
    {
      type: 'player.attack',
      label: 'Player Attack',
      description: 'Player attacks an enemy',
      defaultData: { damage: 75, targetType: 'enemy', weapon: 'sword', isCritical: false },
    },
    {
      type: 'player.damaged',
      label: 'Player Damaged',
      description: 'Player receives damage',
      defaultData: { hp: 15, damageReceived: 30, source: 'enemy' },
    },
    {
      type: 'player.died',
      label: 'Player Died',
      description: 'Player health reaches zero',
      defaultData: { killedBy: 'dragon', zone: 'dungeon', level: 12 },
    },
    {
      type: 'enemy.spawn',
      label: 'Enemy Spawn',
      description: 'An enemy spawns in the world',
      defaultData: { type: 'elite', name: 'Shadow Knight', level: 15 },
    },
    {
      type: 'item.pickup',
      label: 'Item Pickup',
      description: 'Player picks up an item',
      defaultData: { type: 'potion', name: 'Health Potion', rarity: 'common' },
    },
    {
      type: 'zone.enter',
      label: 'Zone Enter',
      description: 'Player enters a new zone',
      defaultData: { zone: 'fire', dangerLevel: 8, hasEnemies: true },
    },
    {
      type: 'boss.defeated',
      label: 'Boss Defeated',
      description: 'A boss is defeated',
      defaultData: { bossName: 'Fire Dragon', xpReward: 5000, zone: 'volcano' },
    },
  ],
  actions: [
    { type: 'play_sound', label: 'Play Sound', description: 'Plays a sound effect' },
    { type: 'show_floating_text', label: 'Show Floating Text', description: 'Shows floating damage/text on screen' },
    { type: 'apply_dot_damage', label: 'Apply DoT Damage', description: 'Applies damage over time to player' },
    { type: 'show_vfx', label: 'Show VFX', description: 'Shows a visual effect' },
    { type: 'spawn_boss', label: 'Spawn Boss', description: 'Spawns a boss enemy' },
    { type: 'play_music', label: 'Play Music', description: 'Changes the background music' },
    { type: 'show_warning_ui', label: 'Show Warning UI', description: 'Shows a low HP warning overlay' },
    { type: 'show_death_screen', label: 'Show Death Screen', description: 'Shows the game over screen' },
    { type: 'save_stats', label: 'Save Stats', description: 'Saves player statistics' },
    { type: 'drop_rare_loot', label: 'Drop Rare Loot', description: 'Drops a rare item' },
    { type: 'restore_hp', label: 'Restore HP', description: 'Restores player health' },
    { type: 'award_xp', label: 'Award XP', description: 'Awards experience points' },
    { type: 'unlock_achievement', label: 'Unlock Achievement', description: 'Unlocks an achievement' },
  ],
  rules: [
    {
      id: 'critical_hit',
      label: 'Critical Hit',
      description: 'When player attacks with damage > 50, play critical sound and show floating text',
      group: 'combat',
      priority: 10,
      events: ['player.attack'],
      matchMode: 'All',
      conditions: ['damage gt 50'],
      actions: ['play_sound', 'show_floating_text'],
    },
    {
      id: 'fire_zone_damage',
      label: 'Fire Zone Damage',
      description: 'When entering the fire zone, apply DoT damage and show flames VFX',
      group: 'zones',
      priority: 8,
      events: ['zone.enter'],
      matchMode: 'All',
      conditions: ['zone eq fire'],
      actions: ['apply_dot_damage', 'show_vfx'],
    },
    {
      id: 'boss_room',
      label: 'Boss Room Entry',
      description: 'When entering boss_room zone, spawn boss and play boss music',
      group: 'zones',
      priority: 9,
      events: ['zone.enter'],
      matchMode: 'All',
      conditions: ['zone eq boss_room'],
      actions: ['spawn_boss', 'play_music'],
    },
    {
      id: 'player_low_hp',
      label: 'Player Low HP',
      description: 'When player is damaged and HP < 20, show warning and play heartbeat',
      group: 'combat',
      priority: 7,
      events: ['player.damaged'],
      matchMode: 'All',
      conditions: ['hp lt 20'],
      actions: ['show_warning_ui', 'play_sound'],
    },
    {
      id: 'player_death',
      label: 'Player Death',
      description: 'When player dies, show death screen and save stats',
      group: 'combat',
      priority: 10,
      events: ['player.died'],
      matchMode: 'All',
      conditions: [],
      actions: ['show_death_screen', 'save_stats'],
    },
    {
      id: 'elite_loot_drop',
      label: 'Elite Loot Drop',
      description: 'When an elite enemy spawns, drop rare loot',
      group: 'loot',
      priority: 5,
      events: ['enemy.spawn'],
      matchMode: 'All',
      conditions: ['type eq elite'],
      actions: ['drop_rare_loot'],
    },
    {
      id: 'potion_heal',
      label: 'Potion Heal',
      description: 'When picking up a potion, restore HP and play heal sound',
      group: 'items',
      priority: 6,
      events: ['item.pickup'],
      matchMode: 'All',
      conditions: ['type eq potion'],
      actions: ['restore_hp', 'play_sound'],
    },
    {
      id: 'boss_victory',
      label: 'Boss Victory',
      description: 'When a boss is defeated, award XP, unlock achievement, and play victory sound',
      group: 'combat',
      priority: 10,
      events: ['boss.defeated'],
      matchMode: 'All',
      conditions: [],
      actions: ['award_xp', 'unlock_achievement', 'play_sound'],
    },
  ],
};
