import type { ScenarioConfig } from '../types';

export const smartHomeConfig: ScenarioConfig = {
  id: 'smartHome',
  icon: 'Home',
  color: '#51cf66',
  events: [
    {
      type: 'sensor.temperature',
      label: 'Temperature Reading',
      description: 'Temperature sensor reports a reading',
      defaultData: { temp: 32, room: 'living_room', unit: 'celsius' },
    },
    {
      type: 'sensor.motion',
      label: 'Motion Detected',
      description: 'Motion sensor triggers',
      defaultData: { room: 'hallway', time: 23, confidence: 0.95 },
    },
    {
      type: 'sensor.door',
      label: 'Door Sensor',
      description: 'Door open/close sensor triggers',
      defaultData: { state: 'open', door: 'front', nobody_home: true },
    },
    {
      type: 'device.status',
      label: 'Device Status',
      description: 'A smart device reports its status',
      defaultData: { status: 'offline', device: 'smart_speaker', lastSeen: '5min ago' },
    },
    {
      type: 'schedule.trigger',
      label: 'Schedule Trigger',
      description: 'A scheduled automation triggers',
      defaultData: { schedule: 'morning', time: 7, day: 'Monday' },
    },
    {
      type: 'alarm.triggered',
      label: 'Alarm Triggered',
      description: 'Security alarm is triggered',
      defaultData: { zone: 'perimeter', severity: 'high', sensor: 'window_sensor' },
    },
    {
      type: 'energy.reading',
      label: 'Energy Reading',
      description: 'Energy meter reports consumption',
      defaultData: { watts: 3500, source: 'main_meter', peak: true },
    },
  ],
  actions: [
    { type: 'turn_on_ac', label: 'Turn On AC', description: 'Activates the air conditioning system' },
    { type: 'send_notification', label: 'Send Notification', description: 'Sends a push notification to phone' },
    { type: 'dim_lights', label: 'Dim Lights', description: 'Adjusts light brightness' },
    { type: 'send_alert', label: 'Send Alert', description: 'Sends a security alert' },
    { type: 'activate_camera', label: 'Activate Camera', description: 'Turns on security camera recording' },
    { type: 'reduce_brightness', label: 'Reduce Brightness', description: 'Reduces overall brightness to save energy' },
    { type: 'log_warning', label: 'Log Warning', description: 'Logs a warning to the system' },
    { type: 'open_blinds', label: 'Open Blinds', description: 'Opens window blinds' },
    { type: 'start_coffee', label: 'Start Coffee', description: 'Starts the coffee machine' },
    { type: 'play_music', label: 'Play Music', description: 'Plays music on smart speakers' },
    { type: 'lock_doors', label: 'Lock Doors', description: 'Locks all smart locks' },
    { type: 'arm_alarm', label: 'Arm Alarm', description: 'Arms the security alarm' },
    { type: 'dim_all', label: 'Dim All Lights', description: 'Dims all lights to minimum' },
    { type: 'sirens_on', label: 'Sirens On', description: 'Activates security sirens' },
    { type: 'notify_security', label: 'Notify Security', description: 'Notifies security company' },
    { type: 'record_cameras', label: 'Record Cameras', description: 'Starts recording all cameras' },
    { type: 'attempt_restart', label: 'Attempt Restart', description: 'Attempts to restart the offline device' },
  ],
  rules: [
    {
      id: 'ac_auto_on',
      label: 'AC Auto On',
      description: 'When temperature > 28°C, turn on AC and notify',
      group: 'climate',
      priority: 8,
      events: ['sensor.temperature'],
      matchMode: 'All',
      conditions: ['temp gt 28'],
      actions: ['turn_on_ac', 'send_notification'],
    },
    {
      id: 'motion_lights',
      label: 'Night Motion Lights',
      description: 'When motion in hallway after 10 PM, dim lights to 30%',
      group: 'lighting',
      priority: 6,
      events: ['sensor.motion'],
      matchMode: 'All',
      conditions: ['room eq hallway', 'time gt 22'],
      actions: ['dim_lights'],
    },
    {
      id: 'door_alert',
      label: 'Door Alert',
      description: 'When door opens while nobody home, send alert and activate camera',
      group: 'security',
      priority: 10,
      events: ['sensor.door'],
      matchMode: 'All',
      conditions: ['state eq open', 'nobody_home eq true'],
      actions: ['send_alert', 'activate_camera'],
    },
    {
      id: 'energy_saving',
      label: 'Energy Saving',
      description: 'When energy consumption > 3000W, reduce brightness and log warning',
      group: 'energy',
      priority: 7,
      events: ['energy.reading'],
      matchMode: 'All',
      conditions: ['watts gt 3000'],
      actions: ['reduce_brightness', 'log_warning'],
    },
    {
      id: 'morning_routine',
      label: 'Morning Routine',
      description: 'When morning schedule triggers, open blinds, start coffee, and play music',
      group: 'routines',
      priority: 5,
      events: ['schedule.trigger'],
      matchMode: 'All',
      conditions: ['schedule eq morning'],
      actions: ['open_blinds', 'start_coffee', 'play_music'],
    },
    {
      id: 'night_mode',
      label: 'Night Mode',
      description: 'When night schedule triggers, lock doors, arm alarm, and dim lights',
      group: 'routines',
      priority: 5,
      events: ['schedule.trigger'],
      matchMode: 'All',
      conditions: ['schedule eq night'],
      actions: ['lock_doors', 'arm_alarm', 'dim_all'],
    },
    {
      id: 'alarm_response',
      label: 'Alarm Response',
      description: 'When perimeter alarm triggers, activate sirens, notify security, and record',
      group: 'security',
      priority: 10,
      events: ['alarm.triggered'],
      matchMode: 'All',
      conditions: ['zone eq perimeter'],
      actions: ['sirens_on', 'notify_security', 'record_cameras'],
    },
    {
      id: 'device_offline',
      label: 'Device Offline',
      description: 'When a device goes offline, send alert and attempt restart',
      group: 'maintenance',
      priority: 4,
      events: ['device.status'],
      matchMode: 'All',
      conditions: ['status eq offline'],
      actions: ['send_alert', 'attempt_restart'],
    },
  ],
};
